# Generated by Django 5.2.7 on 2025-10-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='Boutique_app.categorie', verbose_name='Catégorie'),
        ),
    ]
