# Generated by Django 5.2.6 on 2025-11-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique_app', '0002_alter_produit_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduit',
            options={'ordering': ['noImage'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
